version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "80:80"

  onlearn-ui:
    image: ghcr.io/ivanodints/onlearn-ui:latest
    restart: always
    ports:
      - "8080"
    environment:
      MYSQL_HOSTNAME: "db"
    command: bash -c "/apps/wait-for-mysql.sh db && /apps/entrypoint.sh"

  onlearn-admin-ui:
    image: ghcr.io/ivanodints/onlearn-admin-ui:latest
    restart: always
    ports:
      - "8080"
    environment:
      MYSQL_HOSTNAME: "db"
    command: bash -c "/apps/wait-for-mysql.sh db && /apps/entrypoint.sh"

  db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: